// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAufEdLSrT8Zk4TDpj7G4SF37OIZTJML1M',
    appId: '1:655059074478:web:9b314d304de782091e5c3f',
    messagingSenderId: '655059074478',
    projectId: 'rdp-todolist-mavt',
    authDomain: 'rdp-todolist-mavt.firebaseapp.com',
    storageBucket: 'rdp-todolist-mavt.appspot.com',
    measurementId: 'G-6SKZEDR6T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUeWk_GEMqKiLeCrlilL5D0a5a7Bkjx0',
    appId: '1:655059074478:android:2177aa1eae7b1d1a1e5c3f',
    messagingSenderId: '655059074478',
    projectId: 'rdp-todolist-mavt',
    storageBucket: 'rdp-todolist-mavt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFMJGv_rEpqkaiqC603hFaeOKhRmX56rM',
    appId: '1:655059074478:ios:61f5dd5c5e0c7ec41e5c3f',
    messagingSenderId: '655059074478',
    projectId: 'rdp-todolist-mavt',
    storageBucket: 'rdp-todolist-mavt.appspot.com',
    iosBundleId: 'com.example.rdpTodolistMavt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFMJGv_rEpqkaiqC603hFaeOKhRmX56rM',
    appId: '1:655059074478:ios:61f5dd5c5e0c7ec41e5c3f',
    messagingSenderId: '655059074478',
    projectId: 'rdp-todolist-mavt',
    storageBucket: 'rdp-todolist-mavt.appspot.com',
    iosBundleId: 'com.example.rdpTodolistMavt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAufEdLSrT8Zk4TDpj7G4SF37OIZTJML1M',
    appId: '1:655059074478:web:152d54dc669814041e5c3f',
    messagingSenderId: '655059074478',
    projectId: 'rdp-todolist-mavt',
    authDomain: 'rdp-todolist-mavt.firebaseapp.com',
    storageBucket: 'rdp-todolist-mavt.appspot.com',
    measurementId: 'G-5352RKJH37',
  );
}
